

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

# 1. Premenné na začiatku súboru (načítajú sa okamžite)
env = XCURSOR_THEME,Nordzy-cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Nordzy-cursors
env = HYPRCURSOR_SIZE,24

# 2. Opravený príkaz na autostart (vynúti nastavenie na pozadí plochy)
exec-once = hyprctl setcursor Nordzy-cursors 24

input {
    kb_layout = sk
    kb_variant =
    # Toto zabezpečí, že pravý Alt (AltGr) bude fungovať na špeciálne znaky
    kb_options =
}

bind = $mainMod, S, exec, ags toggle launcher
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
